# Generated by Django 4.0 on 2023-06-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='moview',
            new_name='movie',
        ),
    ]
